config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'profile/index'
  get 'dashboard/index'
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'dashboard#index'
  get '/normal_slip', to: 'slips#new', as: 'new_normal_slip'
  post '/normal_slip', to: 'slips#create', as: 'create_normal_slip'
  get '/profile', to: 'profile#index', as: 'show_profile'
  get '/change_password', to: 'profile#change_password', as: 'change_password'
  post '/post_password', to: 'profile#post_password', as: 'post_password'

  resources :users, only: [:new, :create]
  resources :deposit_requests, only: [:new, :create, :index]
  resources :slip_payments, only: [:new, :create]
  resources :transactions, only: [:index]
  get "/medical_centers", to: "medical_centers#index", as: :medical_centers
  get "/medical_index_centers", to: "medical_centers#medical_index"
end

app/models/slip.rb
class Slip < ApplicationRecord
    validates :country, :city, :country_traveling_to, :first_name, :last_name, 
    :dob, :gender, :marital_status, :nationality, :passport_number, 
    :passport_issue_date, :passport_expiry_date, :visa_type, 
    :position_applied_for, presence: true
    validates :passport_number, confirmation: true
    enum slip_type: { normal: 0, night: 1, special: 2 }

    # def self.ransackable_attributes(auth_object = nil)
    #   %w[id user_id country city country_traveling_to first_name last_name dob gender marital_status nationality passport_number confirm_password passport_issue_date passport_expiry_date visa_type national_id position_applied_for remarks confirmation created_at updated_at slip_type user_id transaction_id transaction_type item_type running_balance]
    # end
    def self.ransackable_attributes(auth_object = nil)
      ["city", "confirm_passport", "confirmation", "country", "country_traveling_to", "created_at", "dob", "first_name", "gender", "id", "id_value", "item_type", "last_name", "marital_status", "national_id", "nationality", "passport_expiry_date", "passport_issue_date", "passport_number", "position_applied_for", "remarks", "running_balance", "slip_type", "transaction_id", "transaction_type", "updated_at", "user_id", "visa_type"]
    end
  end
  

app/controllers/slips_controller.rb
class SlipsController < ApplicationController
  before_action :authenticate_user!
  
    def new
      @slip = Slip.new(slip_type: params[:type])
    end
  
    def create
      @slip = Slip.new(slip_params)
      @slip.user_id = current_user.id # Assuming you have a current_user method
      @slip.slip_type = params[:slip][:slip_type]
      if @slip.save
        redirect_to dashboard_index_path, notice: 'Slip created successfully!'
      else
        flash.now[:alert] = 'Error saving the slip.'
        render :new
      end
    end
  
    private
  
    def slip_params
      params.require(:slip).permit(:country, :city, :country_traveling_to, :first_name, :last_name, :dob, :gender, :marital_status, :nationality, :passport_number, :confirm_passport, :passport_issue_date, :passport_expiry_date, :visa_type, :national_id, :position_applied_for, :remarks, :confirmation, :type, :user_id, :medical_center)
    end
  end
  

app/helpers/slips_helper.rb
module SlipsHelper
end

app/views/slips/new.html.erb
<div class="container mt-4">
  <% if params[:type] == 'normal' %>
    <h3 class="text-primary mb-4">Normal Slip</h3>
  <% end %>
    <% if params[:type] == 'night' %>
    <h3 class="text-success mb-4">Night Slip</h3>
  <% end %>
    <% if params[:type] == 'special' %>
    <h3 class="text-info mb-4">Special Slip</h3>
  <% end %>
  <%= form_with model: @slip, url: create_normal_slip_path, local: true, class: "row g-3" do |f| %>
    <%= f.hidden_field :slip_type, value: params[:type] %>
    <div class="col-md-4">
      <%= f.label :country, class: "form-label" %>
      <%= f.select :country, [["Bangladesh", "Bangladesh"]], { prompt: "Select Country" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :city, class: "form-label" %>
      <%= f.select :city, [["Barishal", "Barishal"], ["Chitagong", "Chitagong"], ["Cox's bazar", "Cox's bazar"], ["Cumilla", "Cumilla"], ["Dhaka", "Dhaka"], ["Rajshahi", "Rajshahi"], ["Sherpur", "Sherpur"], ["Sylhet", "Sylhet"]], { prompt: "Select City" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :country_traveling_to, class: "form-label" %>
      <%= f.select :country_traveling_to, [["UAE", "UAE"], ["Saudi Arabia", "Saudi Arabia"], ["Bahrain", "Bahrain"], ["Kuwait", "Kuwait"], ["Oman", "Oman"], ["Qatar", "Qatar"], ["Yemen", "Yemen"]], { prompt: "Select GCC country" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :first_name, class: "form-label" %>
      <%= f.text_field :first_name, class: "form-control", placeholder: "First name", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :last_name, class: "form-label" %>
      <%= f.text_field :last_name, class: "form-control", placeholder: "Last name", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :dob, "Date of Birth", class: "form-label" %>
      <%= f.date_field :dob, class: "form-control", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :gender, class: "form-label" %>
      <%= f.select :gender, [["Male", "Male"], ["Female", "Female"]], { prompt: "Select Gender" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :marital_status, class: "form-label" %>
      <%= f.select :marital_status, [["Single", "Single"], ["Married", "Married"]], { prompt: "Select Marital Status" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :nationality, class: "form-label" %>
      <%= f.select :nationality, [["Bangladesh", "Bangladesh"]], { prompt: "Select Nationality" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :passport_number, class: "form-label" %>
      <%= f.text_field :passport_number, class: "form-control", placeholder: "Passport number", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :confirm_passport, "Confirm Passport", class: "form-label" %>
      <%= f.text_field :confirm_passport, class: "form-control", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :passport_issue_date, class: "form-label" %>
      <%= f.date_field :passport_issue_date, class: "form-control", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :passport_expiry_date, class: "form-label" %>
      <%= f.date_field :passport_expiry_date, class: "form-control", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :visa_type, class: "form-label" %>
      <%= f.select :visa_type, [["Work Visa", "Work Visa"], ["Family Visa", "Family Visa"]], { prompt: "Select Visa Type" }, class: "form-select", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :national_id, "National ID (Optional)", class: "form-label" %>
      <%= f.text_field :national_id, class: "form-control", required: true %>
    </div>

    <% if params[:type] == 'special' %>
      <div class="col-md-4">
        <%= f.label :medical_centre, "Medical Centre", class: "form-label" %>
        <%= f.select :medical_centre, [], { prompt: "Select Medical Centre" }, class: "form-select", id: "medical_centre", required: true %>
      </div>
    <% end %>
    <div class="col-md-4">
      <%= f.label :position_applied_for, "Position Applied For", class: "form-label" %>
      <%= f.select :position_applied_for, 
                  [
                    ["Banking & Finance", "Banking & Finance"],
                    ["Carpenter", "Carpenter"],
                    ["Cashier", "Cashier"],
                    ["Electrician", "Electrician"],
                    ["Engineer", "Engineer"],
                    ["General Secretary", "General Secretary"],
                    ["Health & Medicine & Nursing", "Health & Medicine & Nursing"],
                    ["Heavy Driver", "Heavy Driver"],
                    ["IT & Internet Engineer", "IT & Internet Engineer"],
                    ["Leisure & Tourism", "Leisure & Tourism"],
                    ["Light Driver", "Light Driver"],
                    ["Mason", "Mason"],
                    ["President", "President"],
                    ["Labour", "Labour"],
                    ["Plumber", "Plumber"],
                    ["Doctor", "Doctor"],
                    ["Family", "Family"],
                    ["Steel Fixer", "Steel Fixer"],
                    ["Aluminum Technician", "Aluminum Technician"],
                    ["Nurse", "Nurse"],
                    ["Male Nurse", "Male Nurse"],
                    ["Ward Boy", "Ward Boy"],
                    ["Shovel Operator", "Shovel Operator"],
                    ["Dozer Operator", "Dozer Operator"],
                    ["Car Mechanic", "Car Mechanic"],
                    ["Petrol Mechanic", "Petrol Mechanic"],
                    ["Diesel Mechanic", "Diesel Mechanic"],
                    ["Student", "Student"],
                    ["Accountant", "Accountant"],
                    ["Lab Technician", "Lab Technician"],
                    ["Draftsman", "Draftsman"],
                    ["Auto-Cad Operator", "Auto-Cad Operator"],
                    ["Painter", "Painter"],
                    ["Tailor", "Tailor"],
                    ["Welder", "Welder"],
                    ["X-ray Technician", "X-ray Technician"],
                    ["Lecturer", "Lecturer"],
                    ["A.C Technician", "A.C Technician"],
                    ["Business", "Business"],
                    ["Cleaner", "Cleaner"],
                    ["Security Guard", "Security Guard"],
                    ["House Maid", "House Maid"],
                    ["Manager", "Manager"],
                    ["Hospital Cleaning", "Hospital Cleaning"],
                    ["Mechanic", "Mechanic"],
                    ["Computer Operator", "Computer Operator"],
                    ["House Driver", "House Driver"],
                    ["Driver", "Driver"],
                    ["Cleaning Labour", "Cleaning Labour"],
                    ["Building Electrician", "Building Electrician"],
                    ["Salesman", "Salesman"],
                    ["Plastermason", "Plastermason"],
                    ["Servant", "Servant"],
                    ["Barber", "Barber"],
                    ["Residence", "Residence"],
                    ["Shepherds", "Shepherds"],
                    ["Employment", "Employment"],
                    ["Fuel Filler", "Fuel Filler"],
                    ["Worker", "Worker"],
                    ["House Boy", "House Boy"],
                    ["House Wife", "House Wife"],
                    ["RCC Fitter", "RCC Fitter"],
                    ["Clerk", "Clerk"],
                    ["Microbiologist", "Microbiologist"],
                    ["Teacher", "Teacher"],
                    ["Helper", "Helper"],
                    ["Hajj Duty", "Hajj Duty"],
                    ["Shuttering", "Shuttering"],
                    ["Supervisor", "Supervisor"],
                    ["Medical Specialist", "Medical Specialist"],
                    ["Office Secretary", "Office Secretary"],
                    ["Technician", "Technician"],
                    ["Butcher", "Butcher"],
                    ["Arabic Food Cook", "Arabic Food Cook"],
                    ["Agricultural Worker", "Agricultural Worker"],
                    ["Service", "Service"],
                    ["Studio CAD Designer", "Studio CAD Designer"],
                    ["Financial Analyst", "Financial Analyst"],
                    ["Cabin Appearance (AIR LINES)", "Cabin Appearance (AIR LINES)"],
                    ["Car Washer", "Car Washer"],
                    ["Surveyor", "Surveyor"],
                    ["Electrical Technician", "Electrical Technician"],
                    ["Waiter", "Waiter"],
                    ["Nursing helper", "Nursing helper"],
                    ["Anesthesia technician", "Anesthesia technician"],
                    ["Marvel", "Marvel"],
                    ["Construction worker", "Construction worker"]
                  ], 
                  { prompt: "Select Position" }, 
                  class: "form-select select2 form-select-md", required: true %>
      </div>
    <div class="col-md-12">
      <%= f.label :remarks, "Your Own Remarks (If Any)", class: "form-label" %>
      <%= f.text_area :remarks, class: "form-control", placeholder: "Remarks, if any" %>
    </div>
    <div class="col-md-12">
      <%= f.check_box :confirmation, required: true %>
      <%= f.label :confirmation, "I confirm that the information given in this form is true, complete and accurate" %>
    </div>
    <div class="col-md-12 text-center mt-3">
      <%= f.submit "Save And Continue", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>