config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'profile/index'
  get 'dashboard/index'
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'dashboard#index'
  get '/normal_slip', to: 'slips#new', as: 'new_normal_slip'
  post '/normal_slip', to: 'slips#create', as: 'create_normal_slip'
  get '/profile', to: 'profile#index', as: 'show_profile'
  get '/change_password', to: 'profile#change_password', as: 'change_password'
  post '/post_password', to: 'profile#post_password', as: 'post_password'

  resources :users, only: [:new, :create]
  resources :deposit_requests, only: [:new, :create, :index]
  resources :slip_payments, only: [:new, :create]
  resources :transactions, only: [:index]
  get "/medical_centers", to: "medical_centers#index", as: :medical_centers
  get "/medical_index_centers", to: "medical_centers#medical_index"
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
end

app/controllers/medical_centers_controller.rb
class MedicalCentersController < ApplicationController
    def index
        @countries = MedicalCenter.pluck(:country).uniq
        @cities = params[:country].present? ? MedicalCenter.where(country: params[:country]).pluck(:city).uniq : []
        @medical_centers = MedicalCenter.all
    
        @medical_centers = @medical_centers.where(country: params[:country]) if params[:country].present?
        @medical_centers = @medical_centers.where(city: params[:city]) if params[:city].present?
        @medical_centers = @medical_centers.where("center_name ILIKE ?", "%#{params[:center_name]}%") if params[:center_name].present?
    end

    def medical_index
        country = params[:country]
        city = params[:city]
        
        if country.present? && city.present?
          centres = MedicalCenter.where(country: country, city: city).pluck(:id, :center_name)
          render json: { centres: centres.map { |id, center_name| { id: id, name: center_name } } }
        else
          render json: { centres: [] }
        end
    end
end

app/helpers/medical_centers_helper.rb
module MedicalCentersHelper
end

app/views/medical_centers/index.html.erb
<!-- app/views/medical_centers/index.html.erb -->
<div class="container mt-4">
  <h1 class="mb-4">Medical Centers</h1>

  <!-- Filters Form -->
  <form method="get" action="<%= medical_centers_path %>" class="mb-4">
    <div class="row">
      <div class="col-md-3">
        <label for="country" class="form-label">Country</label>
        <select name="country" id="country" class="form-select" onchange="this.form.submit()">
          <option value="">Select Country</option>
          <% @countries.each do |country| %>
            <option value="<%= country %>" <%= 'selected' if params[:country] == country %>><%= country %></option>
          <% end %>
        </select>
      </div>

      <div class="col-md-3">
        <label for="city" class="form-label">City</label>
        <select name="city" id="city" class="form-select">
          <option value="">Select City</option>
          <% @cities.each do |city| %>
            <option value="<%= city %>" <%= 'selected' if params[:city] == city %>><%= city %></option>
          <% end %>
        </select>
      </div>

      <div class="col-md-3">
        <label for="center_name" class="form-label">Center Name</label>
        <input type="text" name="center_name" id="center_name" class="form-control" placeholder="Enter Center Name" value="<%= params[:center_name] %>">
      </div>

      <div class="col-md-3 d-flex align-items-end">
        <button type="submit" class="btn btn-primary w-100">Apply Filters</button>
      </div>
    </div>
  </form>

  <!-- Table -->
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Center Name</th>
        <th>Country</th>
        <th>City</th>
        <th>Traveling Country</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @medical_centers.each do |center| %>
        <tr>
          <td><%= center.center_name %></td>
          <td><%= center.country %></td>
          <td><%= center.city %></td>
          <td><%= center.traveling_country %></td>
          <td><%= number_to_currency(center.price, unit: "৳") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>