config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'profile/index'
  get 'dashboard/index'
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'dashboard#index'
  get '/normal_slip', to: 'slips#new', as: 'new_normal_slip'
  post '/normal_slip', to: 'slips#create', as: 'create_normal_slip'
  get '/profile', to: 'profile#index', as: 'show_profile'
  get '/change_password', to: 'profile#change_password', as: 'change_password'
  post '/post_password', to: 'profile#post_password', as: 'post_password'

  resources :users, only: [:new, :create]
  resources :deposit_requests, only: [:new, :create, :index]
  resources :slip_payments, only: [:new, :create]
  resources :transactions, only: [:index]
  get "/medical_centers", to: "medical_centers#index", as: :medical_centers
  get "/medical_index_centers", to: "medical_centers#medical_index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

         validates :user_id, presence: true, uniqueness: true
         validates :password, presence: true, length: { minimum: 6 }

       def self.ransackable_attributes(auth_object = nil)
              %w[id email user_id created_at updated_at]
       end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deposit_request.rb
class DepositRequest < ApplicationRecord  
  belongs_to :user

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :payment_system, presence: true
  validates :deposited_date, presence: true

  enum status: { no_balance: 'no-balance', processing: 'processing', link_processing: 'link-processing', completed: 'completed', cancelled: 'cancelled' }, _default: :processing
  has_one_attached :deposit_slip

end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
end

app/models/slip.rb
class Slip < ApplicationRecord
    validates :country, :city, :country_traveling_to, :first_name, :last_name, 
    :dob, :gender, :marital_status, :nationality, :passport_number, 
    :passport_issue_date, :passport_expiry_date, :visa_type, 
    :position_applied_for, presence: true
    validates :passport_number, confirmation: true
    enum slip_type: { normal: 0, night: 1, special: 2 }

    # def self.ransackable_attributes(auth_object = nil)
    #   %w[id user_id country city country_traveling_to first_name last_name dob gender marital_status nationality passport_number confirm_password passport_issue_date passport_expiry_date visa_type national_id position_applied_for remarks confirmation created_at updated_at slip_type user_id transaction_id transaction_type item_type running_balance]
    # end
    def self.ransackable_attributes(auth_object = nil)
      ["city", "confirm_passport", "confirmation", "country", "country_traveling_to", "created_at", "dob", "first_name", "gender", "id", "id_value", "item_type", "last_name", "marital_status", "national_id", "nationality", "passport_expiry_date", "passport_issue_date", "passport_number", "position_applied_for", "remarks", "running_balance", "slip_type", "transaction_id", "transaction_type", "updated_at", "user_id", "visa_type"]
    end
  end
  

app/models/slip_payment.rb
class SlipPayment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :plaintext_password

    before_save :store_plaintext_password
    has_secure_password
    validates :userid, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object = nil)
        %w[id userid created_at updated_at]
    end

    private

    def store_plaintext_password
      self.plaintext_password = password if new_record? && password.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
      
      def user_signed_in?
        current_user.present?
      end

      def authenticate_user!
        redirect_to login_path unless current_user
      end
      
      helper_method :current_user, :user_signed_in?      
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login

  def index
  end

  private

  def require_login
    unless session[:user_id]
      redirect_to login_path, alert: 'You must be logged in to access this section'
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end

  def change_password
    @user = current_user
  end

  def post_password
    @user = current_user
    find_user = User.find_by_userid(params[:userid])
  
    if find_user.update(password: params[:password])
      flash.now[:success] = "Password updated successfully!"
    else
      flash.now[:error] = "Failed to update the password. Please try again."
    end
  
    # Re-render the same view to show the flash message
    render :change_password # Replace `:edit_password` with the name of your template
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery except: :create
  #before_action :authenticate_user!
  
  def new
    if current_user.present?
      redirect_to dashboard_index_path
    end
  end

  def create
    user = User.find_by(userid: params[:session][:userid])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, notice: 'Login successful'
    else
      flash.now[:alert] = 'Invalid userid or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully'
  end
end

app/controllers/slips_controller.rb
class SlipsController < ApplicationController
  before_action :authenticate_user!
  
    def new
      @slip = Slip.new(slip_type: params[:type])
    end
  
    def create
      @slip = Slip.new(slip_params)
      @slip.user_id = current_user.id # Assuming you have a current_user method
      @slip.slip_type = params[:slip][:slip_type]
      if @slip.save
        redirect_to dashboard_index_path, notice: 'Slip created successfully!'
      else
        flash.now[:alert] = 'Error saving the slip.'
        render :new
      end
    end
  
    private
  
    def slip_params
      params.require(:slip).permit(:country, :city, :country_traveling_to, :first_name, :last_name, :dob, :gender, :marital_status, :nationality, :passport_number, :confirm_passport, :passport_issue_date, :passport_expiry_date, :visa_type, :national_id, :position_applied_for, :remarks, :confirmation, :type, :user_id, :medical_center)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/deposit_requests_helper.rb
module DepositRequestsHelper
end

app/helpers/medical_centers_helper.rb
module MedicalCentersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slip_payments_helper.rb
module SlipPaymentsHelper
end

app/helpers/slips_helper.rb
module SlipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expressslip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'slips', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'deposit_requests', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
  <% if current_user %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light px-4">
    <a class="navbar-brand" href="/dashboard">
      <img src="<%= asset_path('logo.jpg') %>" alt="Logo" style="width: 40px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">Dashboard</a>
        </li>
        <li class="nav-item">
        <%= link_to "Deposit Request", new_deposit_request_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/deposit_requests">Deposit History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/transactions">Transactions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/medical_centers">Medical Center</a>
        </li>
        <li class="nav-item">
          <%= link_to "profile", profile_index_path, class: "nav-link" %>
        </li>
      </ul>
      <div class="profile-info">
        <span class="badge bg-primary"><%= current_user.userid %>Tk</span>
        <%= link_to 'Logout', logout_path, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </nav>
<% else %>

<% end %>

    <%= yield %>
  </body>
</html>